[package]
name = "times-to-time"
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
version.workspace = true

[dependencies]
times-to-time-timer.workspace = true
