[package]
name = "times-to-time"
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
times-to-time-timer = { path = "../times-to-time-timer" }
