name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code.
      uses: actions/checkout@v3
    - name: Install latest nightly.
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: nightly
        components: rustfmt, clippy
    - name: Run clippy.
      run: cargo clippy
    - name: Build the project.
      run: cargo build --verbose
    - name: run unit tests.
      run: cargo test --verbose
